= Spatial Uncertainty for Features & Functions (SUFF) Model

This repository contains the source code for an ontology that extends https://docs.ogc.org/is/22-047r1/22-047r1.html[GeoSPARQL 1.1] to represent uncertainty in the location of geometric features, supporting cartographic representations as well as analytical functions.

This ontology is described in the forthcoming paper submitted to https://i3mainz.github.io/GeoLD2024/[GeoLD2024], the 4th International Workshop on Geospatial Linked Data at https://2024.eswc-conferences.org[ESWC 2024] in May 2024:

* https://github.com/nicholascar/geold24-suff[SUFF @ GeoLD '24]

The ontology is available in RDF within this repository link:ont.ttl[`ont.ttl`] and online in documented form link:spec/00-master.adoc[in this repo] and at:

* *https://w3id.org/suff*

== License & Use

This ontology is made available for use under the https://opensource.org/license/BSD-3-clause[BSD 3-Clause] license.

NOTE: It is hoped that some form of this ontology will become part of the 2024/2025 expected release of https://github.com/orgs/opengeospatial/projects/11[GeoSPARQL 1.3].

== Contact

Please contact the author for more information:

*Nicholas J. Car* +
_Data Architect_ +
KurrawongAI +
nick@kurrawong.ai +
https://kurrawong.ai +
& +
Australian National University +
nicholas.car@anu.edu.au +
https://researchers.anu.edu.au/researchers/car-n +
