= Spatial Uncertainty & Fuzzy Feature Elements Representation (SUFFER) Ontology

This repository contains the source code for an ontology that extends https://docs.ogc.org/is/22-047r1/22-047r1.html[GeoSPARQL 1.1] to cater for uncertainty, fuzziness and probabilistic functions.

This ontology is described in the forthcoming paper submitted to [GeoLD2024](https://i3mainz.github.io/GeoLD2024/), the 4th International Workshop on Geospatial Linked Data at [ESWC 2024](https://2024.eswc-conferences.org) in May 2024:

* https://github.com/nicholascar/geold24-suffer[SUFFER @ GeoLD '24]

The ontology is available in RDF within this repository - `suffer.ttl` and online in documented form at:

* https://nicholascar.github.io/suffer-ont/[https://w3id.org/suffer]

== License & Use

This ontology is made available for use under the https://opensource.org/license/BSD-3-clause[BSD 3-Clause] license.

NOTE: It is hoped that some form of this ontology will become part of the 2024/2025 expected release of https://github.com/orgs/opengeospatial/projects/11[GeoSPARQL 1.3].

== Contact

Please contact the author for more information:

*Nicholas J. Car* +
_Data Architect_ +
KurrawongAI +
nick@kurrawong.ai +
https://kurrawong.ai +
& +
Australian National University +
nicholas.car@anu.edu.au +
https://researchers.anu.edu.au/researchers/car-n +
