== Introduction

This model introduces a systematic way of arranging and describing <<GEO, GeoSPARQL>>.

=== Sources of Requirements

The motivation for this model was the need, in multiple projects in 2022 - 2024, to represent the spatiality (geometry) of features with uncertainty. For example, to represent the First Nations people of Australia's traditional homeland areas: these are hot known with precise boundaries.

<<GEO, GeoSPARQL 1.1>> defines spatial https://docs.ogc.org/is/22-047r1/22-047r1.html#_class_geofeature[`Features`] and https://docs.ogc.org/is/22-047r1/22-047r1.html#_geometry_class[`Geometry`] classes and even a https://docs.ogc.org/is/22-047r1/22-047r1.html#_class_geogeometrycollection[`Geometry Collection`] class which can be used to associate multiple geometries with a feature. This is the core of this model since multiple geometries for a feature can be used to convey location uncertainty in several ways - see the <<Major Modelling Principles> below.

GeoSPARQL 1.1 does not, however, provide all the elements needed for deterministic representations of feature location uncertainty, nor does GeoSPARQL 1.1 describe how to perform topological functions on features with uncertain location representation. This model defines conventions for GeoSPARQL 1.1 element use, and introduces several new model elements, for this purpose.

=== Major Modelling Principles

=== Uncertainty in position only

This model only directly addresses uncertainty in the position of spatial features. It does not address uncertainty in the values of other feature properties. For example, if a map of average daily temperature for a region was modelled using GeoSPARQL 1.1 and this model's elements, uncertainty in the measurement of the temperature values themselves would be out of scope.

NOTE:: Many other ontologies provide for the representation of measurement uncertain and simple models such as <<SDO, schema.org>> include properties such as https://schema.org/marginOfError[marginOfError] for this purpose.

=== Display rules

This model defines a number of rules that define the manner in which the spatial representation of features - a collection of geometries - is to be interpreted for display.

These rules are based on the instructions on the level of measurement relationship between the geometries in a geometry collection contained within the data. The relationship is either conveyed directly in the data by use of the <<levelOfMeasurement, level of measurement>> predicate, or it is divined from other properties of the geometries.

The levels of measurement are defined in the <<Levels of Measurement, Levels of Measurement>> vocabulary in the <<Supporting Vocabularies>> section of this model.

==== Rule: Nominal geometries

==== Rule: Ordinal geometries

==== Rule: Interval geometries

==== Rule: Ratio geometries

=== Probabilistic Topological Functions

The <<GEO, GeoSPARQL>> standard provides both an ontology which defines spatial elements and predicates to indicate topological relationships between them and also function definitions that can be used to calculate those predicates.

For example, the predicate https://docs.ogc.org/is/22-047r1/22-047r1.html#sf_relations[`geo:sfWithin`] indicated that its subject is spatially _within_ its object where _within_ is the Simple Features Within relation defined by <<OGC-06-103r4>>. The related GeoSPARQL function is http://www.opengis.net/def/function/geosparql/sfWithin[`geof:sfWithin] which defines the parameters and results from the function used to calculate the `geo:sfWithin` relation between two spatial objects.

This model indicates how to calculate the https://docs.ogc.org/is/22-047r1/22-047r1.html#sf_relations[Simple Features relations] between features whose position is uncertain and represented using elements from this model. The general method is described below and specific topological relation calculations follow.

==== General method for probabilistic topological function calculation

For a spatial feature `A` with certain position - a single geometry - and spatial feature `B` with uncertain geometry - as conveyed by this model - calculate a simple feature relation `R` as follows:

. Determine the level of measurement `B_l` for the geometries of `B`
... If `B_l` is <<Levels of Measurement, nominal>>,
.... For each geometry `BG_i` of `B`, calculate `A R BG_i` for each geometry
.... If any `A R BG_i` is `true` then `A R B` is `true`
.... Else it is `false`
... If `B_l` is <<Levels of Measurement, ordinal>>,
.... For each geometry `BG_i` of `B`, calculate `A R BG_i` for each geometry in order




.... Starting with the first geometry `BG_1` and proceeding to the last, `BG_N`, calculate `A R BG_i` for each geometry
..... If
... If `B_l` is <<Levels of Measurement, interval>>,
... If `B_l` is <<Levels of Measurement, ratio>>,

[[table-order]]
.Order of geometry calculation per function
|===
| SF Relation | Order

| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[equals] | -
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[disjoint] | lowest to highest
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[intersects] | highest to lowest
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[touches] | lowest to highest
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[within] | lowest to highest
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[contains] | highest to lowest
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[overlaps] | any
| https://docs.ogc.org/is/22-047r1/22-047r1.html#_simple_features_relation_family[crosses] | any
|===



=== Model resources

This document is this model's "Specification" which is its authoritative, human-readable, definition document. This model also contains other resources with other roles:

[width="75%", cols="2,1,4"]
|===
| Resource | Role | Notes

| https://w3id.org/suffer/ont.ttl[Ontology] | _Schema_ | The technical, machine-readable, version of this model
| <<Supporting Vocabularies>> | _Vocabulary_ | The codelist vocabularies developed for this model and links to others defined elsewhere but expected to be used by this model
| <<AnnexA>> & https://w3id.org/suffer/validator.ttl[Validator] | _Validation_ | The machine-readable validator file used to validate data claiming conformance to this model
| <<AnnexB>> | _Example_ | Examples of data conforming, and some not conforming, to this model
|===
